name: Publish Docker image

on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*.*.*'  # 只在推送版本标签时触发

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4  # 升级到 v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3  # 添加 buildx 支持

      - name: Log in to Docker Hub
        uses: docker/login-action@v3  # 升级到 v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5  # 升级到 v5
        with:
          images: lanyi1998/dnslog-go
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5  # 升级到 v5 解决废弃警告
        with:
          context: .
          platforms: linux/amd64,linux/arm64  # 支持多平台构建
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha  # 启用 GitHub Actions 缓存
          cache-to: type=gha,mode=max